//  Copyright (C) 2001-2007, Evolution Robotics, Inc.
//  Any reproduction is strictly prohibited without the explicit
//  written permission of Evolution Robotics, Inc.  All rights reserved.


#include <evolution/core/resource/CameraParameters.hpp>
#include <evolution/core/resource/CameraUtils.hpp>
#include <evolution/core/resource/Colorspace.hpp>
#include <evolution/core/resource/ColorspaceConverter.hpp>
#include <evolution/core/resource/Image.hpp>
#include <evolution/core/resource/ImageIO.hpp>
#include <evolution/core/resource/ResourceConfigParser.hpp>
#include <evolution/core/resource/ResourceConfigTypes.hpp>
#include <evolution/core/resource/AudioTypes.hpp>
#include <evolution/core/resource/CameraImpl.hpp>
#include <evolution/core/resource/IAnalogPort.hpp>
#include <evolution/core/resource/IAudioBase.hpp>
#include <evolution/core/resource/IAudioCallback.hpp>
#include <evolution/core/resource/IAudioChannel.hpp>
#include <evolution/core/resource/IAudioChannelFactory.hpp>
#include <evolution/core/resource/IAudioLevel.hpp>
#include <evolution/core/resource/IAudioMixer.hpp>
#include <evolution/core/resource/IAudioPlay.hpp>
#include <evolution/core/resource/IAudioRecord.hpp>
#include <evolution/core/resource/IAuthenticator.hpp>
#include <evolution/core/resource/IAvoidance.hpp>
#include <evolution/core/resource/IBattery.hpp>
#include <evolution/core/resource/IBumpSensor.hpp>
#include <evolution/core/resource/IBus.hpp>
#include <evolution/core/resource/IButton.hpp>
#include <evolution/core/resource/IButtonCallback.hpp>
#include <evolution/core/resource/ICamera.hpp>
#include <evolution/core/resource/IDigitalPort.hpp>
#include <evolution/core/resource/IDock.hpp>
#include <evolution/core/resource/IDriveSystem.hpp>
#include <evolution/core/resource/IERRangeSensor.hpp>
#include <evolution/core/resource/IFace.hpp>
#include <evolution/core/resource/IGripper.hpp>
#include <evolution/core/resource/IJoystick.hpp>
#include <evolution/core/resource/ILaserSensor.hpp>
#include <evolution/core/resource/IMotorCommand.hpp>
#include <evolution/core/resource/IMotorQuery.hpp>
#include <evolution/core/resource/IOdometry.hpp>
#include <evolution/core/resource/IPollable.hpp>
#include <evolution/core/resource/IRangeSensor.hpp>
#include <evolution/core/resource/IResourceCallback.hpp>
#include <evolution/core/resource/IResourceContainer.hpp>
#include <evolution/core/resource/IResourceDriver.hpp>
#include <evolution/core/resource/ISerialBus.hpp>
#include <evolution/core/resource/ISpatialSensor.hpp>
#include <evolution/core/resource/ISpeechRecognizer.hpp>
#include <evolution/core/resource/ISpeechRecognizerCallback.hpp>
#include <evolution/core/resource/ISpeechTTS.hpp>
#include <evolution/core/resource/ISpeechTTSCallback.hpp>
#include <evolution/core/resource/ISwitchDevice.hpp>
#include <evolution/core/resource/ITextWindow.hpp>
#include <evolution/core/resource/ITransactable.hpp>
#include <evolution/core/resource/IWireless.hpp>
#include <evolution/core/resource/MotionConstants.hpp>
#include <evolution/core/resource/OdometryImpl.hpp>
#include <evolution/core/resource/PollableImpl.hpp>
#include <evolution/core/resource/RangeData.hpp>
#include <evolution/core/resource/RangeScan.hpp>
#include <evolution/core/resource/RasterMap.hpp>
#include <evolution/core/resource/RecognizerTypes.hpp>
#include <evolution/core/resource/ResourceCallbackImpl.hpp>
#include <evolution/core/resource/ResourceDriverImpl.hpp>
#include <evolution/core/resource/ResourceManager.hpp>
#include <evolution/core/resource/ResourceRegistry.hpp>
#include <evolution/core/resource/ResourceUtils.hpp>
#include <evolution/core/resource/TTSTypes.hpp>
